[[- $projectName := .Name -]][[- range $deploymentName, $deployment := .Deployments]]
{{ if .Values.secrets.[[$deploymentName]] }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: [[$projectName]]-[[$deploymentName]]-secret
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.secrets.[[$deploymentName]] }}
      {{$key }}: {{$value | quote }}
      {{- end }}
{{end}}
[[- end]]

