[[- $deploymentName := .Name -]][[- $projectName := .ProjectName -]]
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: [[$projectName]]-[[$deploymentName]]-secret
  namespace: {{ .Values.namespace }}
spec:
  encryptedData: [[range $key, $value := .Secrets]]
    [[$key]]: "[[$value]]"
    [[- end -]]
