[[- $projectName := .Name -]][[- range $deploymentName, $deployment := .Deployments]]
{{if .Values.secrets.[[$deploymentName]] }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: [[$projectName]]-[[$deploymentName]]-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "[[ $projectName ]].labels" . | nindent 4 }}
    app.kubernetes.io/component: [[$deploymentName]]
    app: [[ $projectName ]]-[[$deploymentName]]
data:
  {{- range $key, $value := .Values.secrets.[[$deploymentName]] }}
    {{$key }}: {{$value | quote }}
  {{- end }}
{{end}}
[[- end]]
