[[- $deploymentName := .Name -]][[- $projectName := .ProjectName -]]
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: [[$projectName]]-[[$deploymentName]]-secret
  namespace: {{ .Values.namespace }}
data: [[range $key, $value := .Secrets]]
  [[$key]]: "[[$value]]"
  [[- end -]]
