---[[$env := .Environment]]
images:
  tag: [[$env]]-latest
namespace: [[or .Entity.K8.Namespace .Entity.Name]]-[[.Environment]]
env:[[range $deploymentName, $deployment := .Entity.Deployments ]]
  [[$deploymentName]]:[[ range $containerName, $container := $deployment.Containers ]]
    [[$containerName]]:
      [[- range $envKey, $envs := $container.Env ]]
        [[- if eq $envKey $env -]][[ range $name, $value := $envs ]]
        [[$name]]: "[[$value]]"[[end]]
        [[end -]]
      [[ end -]]
    [[end -]]
  [[end]]
secrets:[[range $deploymentName, $deployment := .Entity.Deployments]]
  [[$deploymentName]]:
    [[- range $envKey, $envs := .Secrets ]]
    [[- if eq $envKey $env -]][[ range $name, $value := $envs ]]
    [[ $name ]]: [[ $value ]][[end]]
    [[end -]]
    [[end -]]
[[- end ]]

hooks:[[range $deploymentName, $deployment := .Entity.Deployments ]]
  [[$deploymentName]]:[[ range $containerName, $container := $deployment.Containers ]]
    [[$containerName]]:
      post-install: [[empty $container.Hooks.PostInstall | ternary "false" "true"]]
      pre-install: [[empty $container.Hooks.PreInstall | ternary "false" "true"]]
      pre-upgrade: [[empty $container.Hooks.PreUpgrade | ternary "false" "true"]]
      post-upgrade: [[empty $container.Hooks.PostUpgrade | ternary "false" "true"]]
      post-rollback: [[empty $container.Hooks.PostRollback | ternary "false" "true"]]
      pre-rollback: [[empty $container.Hooks.PreRollback | ternary "false" "true"]]
  [[end -]]
[[end]]
