{{if .Gitlab.Cache.Paths}}cache:
  paths:
{{range $indexP, $path := .Gitlab.Cache.Paths}}    - {{$path}}
{{end}}{{end}}
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: always
    - when: never

stages:
  - build
  - test
{{$projectName := .Name}} {{$gitlab := .Gitlab}} {{$projectName := .Name}} {{$containers := .Containers}}
{{range $index, $container := $containers}}
build_{{$index}}:
  stage: build
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - chmod +x ./docker/dctl.sh
    - cd docker
    - sh ./dctl.sh build-docker {{$index}}
    - sh ./dctl.sh push-docker {{$index}}
{{end}}
{{range $index, $test := $gitlab.Tests}}
test_{{$test.Name}}:
  stage: test
  allow_failure: {{$test.AllowFailure}}
  image: {{$test.Docker.Image}}:${CI_COMMIT_REF_NAME}
  {{if $test.Scripts}}script:
  {{range $indexS, $command := $test.Scripts}}  - {{$command}}
  {{end}}{{end}}
  {{if $test.Before}}before_script:
  {{range $indexB, $command := $test.Before}}  - {{$command}}
  {{end}}{{end}}
  {{if $test.After}}after_script:
  {{range $indexA, $command := $test.After}}  - {{$command}}
  {{end}}{{- end}}
  {{if $test.Docker.Build.Args}}variables:{{range $indexArg, $arg := $test.Docker.Build.Args}}
    {{$indexArg}}: {{$arg}}{{end}}{{end}}
{{end}}
