{{if .Gitlab.Cache.Paths}}cache:
  paths:
{{range $indexP, $path := .Gitlab.Cache.Paths}}    - {{$path}}
{{end}}{{end -}}
{{ getGitlabWorkflowString .Gitlab.OnlyWhen }}
{{ $entity := . }}
stages:
  - build
  {{if .Gitlab.Tests}}- test{{end}}
  {{if .Gitlab.Deploy}}- deploy{{end}}
{{$projectName := .Name}} {{$gitlab := .Gitlab}} {{$projectName := .Name}} {{$containers := .Containers}}
{{range $index, $container := $containers}}
build_{{$index}}:
  stage: build
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - chmod +x ./dctl.sh
    - sh ./dctl.sh build-docker {{$index}}
    - sh ./dctl.sh push-docker {{$index}}
{{end -}}
{{range $index, $test := $gitlab.Tests}}
test:{{$test.Name}}:
  stage: test
{{toYaml $test | indent 2 }}
{{end -}}

{{range $index, $deploy := $gitlab.Deploy}}
deploy:{{$deploy.Name}}:
  stage: deploy
  when: manual
  allow_failure: {{$deploy.AllowFailure}}
  {{if $deploy.Docker.Image}}image: {{$deploy.Docker.Image}}{{end -}}
  {{if $deploy.Scripts}}script:
  {{range $indexS, $command := $deploy.Scripts}}  - {{$command}}
  {{end}}{{end -}}
  {{if $deploy.Before}}before_script:
  {{range $indexB, $command := $deploy.Before}}  - {{$command}}
  {{end}}{{end -}}
  {{if $deploy.After}}after_script:
  {{range $indexA, $command := $deploy.After}}  - {{$command}}
  {{end}}{{- end -}}
  {{if $deploy.Only}}only:
  {{range $indexO, $only := $deploy.Only}}  - {{$only}}
  {{end}}{{- end -}}
  {{if $deploy.Docker.Build.Args}}variables:{{range $indexArg, $arg := $deploy.Docker.Build.Args}}
  {{$indexArg}}: {{$arg}}{{end}}{{end}}
{{- end -}}
