{{$deploymentName := .Name}}{{$projectName := .ProjectName}}{{- range $index, $pvc := .Deployment.Pvc }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ $projectName }}-{{ $deploymentName }}
  name: {{$deploymentName}}-pvc-{{$pvc.Name}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ or $pvc.Storage "300Mi" }}
{{end}}
