apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Name}}-volume{{.Index}}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{getHostPath .Volume}}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{.Name}}-claim{{.Index}}
  name: {{.Name}}-claim{{.Index}}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Mi
