apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.ProjectName}}-{{.Name}}-pv{{.Index}}
  labels:
    type: local
spec:
  claimRef:
    name: {{.ProjectName}}-{{.Name}}-pvc{{.Index}}
    namespace: foo
  storageClassName: ""
  capacity:
    storage: {{ or .Storage "300Mi" }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Src }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{.ProjectName}}-{{.Name}}-pvc{{.Index}}
  name: {{.ProjectName}}-{{.Name}}-pvc{{.Index}}
spec:
  volumeName: {{.ProjectName}}-{{.Name}}-pv{{.Index}}
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ or .Storage "300Mi" }}
