{{- $serviceName := .Name -}} {{- $projectName := .ProjectName -}}{{$namespace := .Namespace -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: {{.ProjectName}}-{{$serviceName}}
  name: ingress-{{.ProjectName}}-{{.Name}}
  namespace: {{or $namespace "default"}}
spec:
  rules:
    - http:
        paths:
          {{- range $path := .Deployment.Ingress.Paths }}
          - path: {{$path.Path}}
            pathType: Prefix
            backend:
              service:
                name: {{$projectName}}-{{ $serviceName }}
                port:
                  number: {{$path.Port}}
{{end -}}
