{{- $deploymentName := .Name -}}{{- $projectName := .ProjectName -}}{{$namespace := .Namespace -}}{{$environment := .Environment -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{$projectName}}-{{$deploymentName}}-secret-{{$environment}}
  namespace: {{or $namespace "default"}}-{{$environment}}
spec:
  encryptedData: {{range $key, $value := .Secrets}}
    {{$key}}: "{{$value}}"
    {{- end -}}
