deployments:{{ range $deployName, $deployment := .Deployments }}
  {{$deployName}}:
    secrets:
      containers:{{range $containerName, $container := $deployment.Containers}}
        {{$containerName}}:
          env:
{{end}}{{end}}