{{- $deploymentName := .Name -}}{{- $projectName := .ProjectName -}}{{$namespace := .Namespace -}}{{$environment := .Environment -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{$projectName}}-{{$deploymentName}}-secret-{{$environment}}
  namespace: {{or $namespace "default"}}-{{$environment}}
data: {{range $key, $value := .Secrets}}
  {{$key}}: "{{$value}}"
  {{- end -}}
