apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Name}}
  name: {{.Name}}
spec:
  ports:
    {{ range $index, $value := .Ports }}
    - name: "{{getPortTwo $value}}"
      port: {{getPortOne $value}}
      targetPort: {{getPortTwo $value}}
  {{end -}}
  selector:
    app: {{.Name}}
  clusterIP: None

