apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .ProjectName }}-{{ .Name }}
  name: {{.ProjectName}}-{{.Name}}
spec:
  ports:
    {{- range $containerName, $container := .Deployment.Containers}}{{ range $index, $value := .Ports }}
    - name: "{{getPortTwo $value}}"
      port: {{getPortOne $value}}
      targetPort: {{getPortTwo $value}}
    {{end}}{{- end}}
  selector:
    app: {{ .ProjectName }}-{{ .Name }}
  type: ClusterIP
