---
version: '3'
{{$projectName := .Name}}
services:
{{range $index, $container := .Containers}}  {{$index}}:
    container_name: {{$projectName}}_{{$index}}
    image: {{$projectName}}/{{$index}}:prod-latest
    {{ if $container.Command }}command: ["{{ join `", "` $container.Command }}"]
    {{end}}
    {{- if $container.Ports}}ports:
      {{ range $container.Ports}}- "{{ . }}"
      {{ end}}
    {{ end}}
    {{- if $container.Volumes}}volumes:
      {{range $container.Volumes}}- {{ . }} 
      {{end}}
    {{ end}}
    {{- if $container.Links}}links:
      {{range $container.Links}}- {{ . }} 
      {{end}}
    {{ end}}
    {{- if $container.Restart}}restart: {{$container.Restart}}
    {{end}}
    {{- if $container.DependsOn}}depends_on:
      {{range $container.DependsOn}}- {{.}}
      {{end}}
    {{end}}
    {{- if $container.Build.Args}}environment:
      {{range $index, $env := $container.Environment}}{{$index}}: {{$env}} 
      {{end}}
    {{- end}}
{{end}}